### ISSUE TITLE
04 -- Rosa Lopez Sanchez.

### ISSUE THREAD

**Issue by rosalsm** [TIY-Durham/2015-FALL-FEE#108]
- **Yak Shaving**
  - [x] Create a new _WIP Issue_ in the class repo... Whaddya name it?
  - [x] Create a new _WIP Branch_ in `TIY-Assignments` named `04--return-of-the-string`
  - Create new _WIP Files_ in `TIY-Assignments` named:
    - [x] `ROT13.js` for the **ROT13** kata
    - [x] `3s-and-5s.js` for the **3s and 5s** kata
    - [x] `EvenFibonaccis.js` for the **Even Fibonaccis** kata
    - [x] `APIGymnastics` (a folder) with these _inside_:
      - [x] `Etsy.js`
      - [x] `items.json`
  - _COMMIT AND PUSH_ :confused:
  - Open a PR in `TIY-Assignments` _from_ `FILL_ME_IN` _into_ `FILL_ME_IN`
  - Add a link to your PR as a comment in your _WIP Issue_!
- **Reading JavaScript**
  - [x] 2 more entries!
  - [x] 5 more entries!
  - [x] 10 more entries!
  - [x] `Array` literal with examples
  - [x] `length` with examples
  - [x] 2 `Array.prototype` methods!
  - **Coding Kata: ROT13**
  - [x] **A quick game of Reversi, perhaps?**
    - [x] Nothing looks the same from every side.
    - [x] "A" single edge makes you sharp.
    - [x] Ironically, both commands exist!
    - [x] Back up and pick a card?
    - [x] Velma was my favorite, too.
    - [x] Just back away.
  - [x] **Worst password generator ever...**
    - [x] Contemplate a single character...
    - [x] What is "it"...?
    - [x] How do you scramble a feline?
    - [x] Technically, four letters should not be harder than three...
    - [x] Hey, you haven't been trying to decode these, too, have you?
    - [x] And "hello" to you, too!
  - [ ] **BEAST MODE** -- Dirty ROT-N Scoundrels
    - [ ] Go easy: start with 13
    - [ ] Well, 0 would be easier, I guess.
    - [ ] I guess 1 isn't so hard, either.
    - [ ] Now, how would I _omit_ the 13?
  - **Coding Kata: 3s and 5s**
  - [x] Got any 3s...?
    - [x] below 10?
    - [x] below 20?
    - [x] below 50?
  - [x] How about 5s...?
    - [x] below 10?
    - [x] below 20?
    - [x] below 50?
  - Sum of 3s and 5s...
    - [x] less than 10?
    - [x] less than 20?
    - [x] less than 50?
    - [x] LESS THAN 1000!?
- [ ] **Coding Kata: Even Fibonacci Sums**
  - **Fibonacci _Sequence_ means `Array`, right?**
    - [x] There are no Fibonacci's less than 0
    - [x] That first term is hard.
    - [x] Maybe the second one, too.
    - [x] The next five terms are easy.
    - [x] ALL THE FIBONACCIS ARE MINE TO CONTROL!
  - **Now about those _even_ terms...**
    - [x] An empty list contains no `evens`
    - [x] There is no number of `1`'s that are even...
    - [x] Y'know what _is_ even?
    - [x] Y'know what _ain't_ even?
    - [x] Do you write your _own_ test cases? Whoah.
  - **Adding things seems easy enough...**
    - [x] Adding _nothing_ is even easier!
    - [x] So adding `1` thing to nothing isn't so bad...
    - [x] Startin' to get complicated...
    - [x] Maybe you wanna... Oh, look you did!
  - **Chain chain chain!**
    - [x] What's the sum of the even terms in the smallest Fibonacci sequence?
    - [x] Do you know of any _other_ sequences?
  - [ ] **BEAST MODE** -- 4 million. Go.
- [ ] **API Gymnastics**
  - **Yak Shaving**
    - [ ] Create your _WIP Branch_! Maybe even check it out?
    - [ ] Create a folder named `APIGymnastics`
    - [ ] Copy-pasta **Starting Point** in `APIGymnastics/Etsy.js`
    - [ ] Hey, what about that data?
    - [ ] Seems like a good time to commit and push...
    - [ ] Y'know, why not open a PR, too?
  - **So many questions...**
    - [ ] What is the total number of items?
    - [ ] What is the average price of all the items?
    - [ ] What items cost between $14 and $18 dollars? What are their names?
    - [ ] What is the name and price of the only item with a `GBP` currency code?
    - [ ] What are the names of all the items made of wood?
    - [ ] What are the names of the items that are made of 8 or more materials?
    - [ ] How many items were made by their sellers?

**Comment by rosalsm** [comment]
Problems with git push. I will try to solve it later but for now this is my work.

3s-and-5s.js

var test = require('mocha').it,
    expect = require('chai').expect, // Use `expect(X).to.be` et al
    assert = require('chai').assert;  // OR use `assert.equal` etc


test(multOf3s, function(){
  expect(multOf3s(5)).to.equal(3);
  expect(multOf3s(6)).to.equal(9);
  expect(multOf3s (10)).to.equal(18);
  expect(multOf3s (12)).to.equal(30);
  expect(multOf3s (0)).to.equal(0);
  expect(multOf3s (20)).to.equal(63);

}); // END test 3s
// function for sum of multiples of 3
//parameter N is a Number
// var sum is a number and var n
//returns a number

function multOf3s (N){
  var sum = 0, n = 0;
  for (n=0; n<=N; n++){
    if (n % 3 === 0){
      sum += n;
    }
  }
  return sum;
}

test(multOf5s, function(){
  expect(multOf5s(5)).to.equal(5);
  expect(multOf5s(6)).to.equal(5);
  expect(multOf5s (10)).to.equal(15);
  expect(multOf5s (12)).to.equal(15);
  expect(multOf5s (0)).to.equal(0);
  expect(multOf5s (20)).to.equal(50);
  expect(multOf5s (50)).to.equal(275);
  expect(multOf5s (1000)).to.equal(100500);

});

function multOf5s (N){
  var sum = 0, n = 0;
  for (n=0; n<=N; n++){
    if (n % 5 === 0){
      sum += n;
    }
  }
  return sum;
}

test(multOf3s5s, function(){
  expect(mult3s5s(5)).to.equal(8);
  expect(mult3s5s(10)).to.equal(33);
  expect(mult3s5s(12)).to.equal(45);
  expect(mult3s5s(15)).to.equal(60);
  expect(mult3s5s(0)).to.equal(0);
  expect(mult3s5s(20)).to.equal(98);
  expect(mult3s5s(50)).to.equal(593);
});


function multOf3s5s (N){
  var sum = 0, n = 0
  for (n=0; n<=N; n++){
    if (n % 3 === 0 || n % 5 === 0){
      sum += n;
    }
  }
  return sum
}

**Comment by rosalsm** [comment]
Same with EvenFibonaccis.js

var text = require('mocha').it,
  expects = require('chai').expect;

test('fibonacci', function(){
  expect(fibonacci(1)).to.be.equal([ 1 ]);
  expect(fibonacci(2)).to.be.equal([ 1, 2 ]);
  expect(fibonacci(3)).to.be.equal([ 1, 2, 3 ]);
  expect(fibonacci(4)).to.be.equal([1, 2, 3, 5 ]);
  expect(fibonacci(5)).to.be.equal([ 1, 2, 3, 5, 8 ]);
  expect(fibonacci(6)).to.be.equal([ 1, 2, 3, 5, 8, 13 ]);
  expect(fibonacci(7)).to.be.equal([ 1, 2, 3, 5, 8, 13, 21 ]);
  expect(fibonacci(8)).to.be.equal([ 1, 2, 3, 5, 8, 13, 21, 34 ]);
  expect(fibonacci(9)).to.be.equal([ 1, 2, 3, 5, 8, 13, 21, 34, 55 ]);
  expect(fibonacci(10)).to.be.equal([ 1, 2, 3, 5, 8, 13, 21, 34, 55, 89 ]);
  // ...ad nauseum.
  });

  function fibonacci(N){
    var i, fib=[];
    fib[0]=1;
    fib[1]=2;
    for (i=2; i<N; i++){
      fib[i]=fib[i-1]+fib[i-2];
    }
    return fib
  }

/* Rosa. It is not very clear to me the meaning of even value.
I assume we refer to the arrys created by term 2, term 4,
term 6, etc.*/


test('evens', function(){
  expect(evens(2).to.be.equal([1, 2 ]);
  expect(evens(4).to.be.equal([1, 2, 3, 5]);
  expect(evens(6).to.be.equal([1, 2, 3, 5, 8, 13 ]);
  expect(evens(8).to.be.equal([1, 2, 3, 5, 8, 13, 21, 34]);
  expect(evens(10).to.be.equal([1, 2, 3, 5, 8, 13, 21, 34, 55, 89]);
}); // END test(evens)

function evens(N){
  if (N % 2 === 0){
    var i, fib=[];
    fib[0]=1;
    fib[1]=2;
    for (i=2; i<N; i++){
      fib[i]=fib[i-1]+fib[i-2];
    }
    return fib
  }
}



test('sumList', function(){
  assert.equal(sumList([ ]), 0);
  assert.equal(sumList([ 1 ]), 1);
  assert.equal(sumList([ 1, 2 ]), 3);
  // ...et cetera, et cetera, et cetera.
}); // END test(sum)

// Rosa. Just crazyyyyyyyy talk

Function sumList (){
  var i , sum = 0, fib = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89] ;
  for (i=0; i< (fib.length-1); i++){
      sum += fib[i];
  }
    return sum
}
/*fib = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

  for (var i=0, sum=0; i< (fib.length-1); i++){
      sum += fib[i];
  }
     sum;

     Rosa. This one works!!!!!!!!!!!!!*/


test('summing even Fibonacci numbers?', function(){
  expect( sum(evens(fibonacci(0))) ).to.equal(FILL_ME_IN); // nice.
  // There really should be more code in here...
}); // END test(dat CHAIN tho)

**Comment by rosalsm** [comment]
Same with ROT13.js

/**
 * The function `reverse` computes the reversal
 * of a given `String` (don't copy-pasta!)
 *
 * @param {String} S to reverse
 * @return {String}
 * S is string, i is index, l is letter
 */
 //Rosa string to array .split()|reverse array .reverse()| to.string() Maybe???

function reverse(S){
  var l = ""
    for (var i = S.length-1; i >= 0; i--);
      l += S[i];
      return l
}

console.assert(reverse("") === ""); // Really?

console.assert(reverse("A") === "A"); // Jerk.

console.assert(reverse("cat") === "tac");

console.assert(reverse("ward") === "draw");

console.assert(reverse("books") === "skoob"); // Rokey, dokey...

console.assert(
  reverse("we don't want no trouble") === "elbuort on tnaw t'nod ew"
);

/**
 * Function `encode` accepts a `String` and produces
 * the appropriate ROT13 "encoded" version, i.e. every
 * character in `phrase` is "rotated" ahead by 13 characters.
 *
 * @see String.prototype.charCodeAt
 * @see String.prototype.fromCharCode
 * @see http://en.wikipedia.org/wiki/ROT13
 *
 * // Start with just `phrase`...
 * @param {String} phrase to encode
 * // Add `N` in part 2!
 * // @param {Number} N rotation to apply, default 13
 * @return {String} encoded with ROT13
 */

 
// Rosa.arggggggggg no time no time to thinkkkkkk
var v
function encode(phrase, N ){
    for (var i = 0, L = ""; i<= phrase.length-1; i++){
      if (110>= phrase.charCodeAt(i)>=97){
        return phrase.charCodeAt(i) + N;
      } else {return phrase.charCodeAt(i) - N;
        }
      }
    L += phrase2.fromCharCode(v)
    return L
}

/**
 * Function `decode` accepts a `phrase` and `N` and
 * decoded it appropriately, i.e. every _word_ character
 * in `phrase` is rotated backward by `N` characters.
 *
 * @param {String} phrase to decode
 * @param {Number} N rotation to apply, default 13
 * @return {String} decoded by ROT-N
 */
function decode(phrase, N){
    // YOUR CODE HERE
}

// Produce more examples, please...
console.assert(encode("hello") === "uryyb");
console.assert(encode("uryyb") === "hello");

console.assert(encode("hello", 2) === "jgnnq")
console.assert(decode("jgnnq", 2) === "hello")

**Comment by rosalsm** [comment]
https://github.com/rosalsm/TIY-Assignments/pull/4

**Comment by kellymurray** [comment]
Changed from Incomplete to Continue Working because:
- I saw that you started `API-Gymnastics`, just didn't get very far in. Also, please remember to check off the boxes as you go.

I can see that you're working really, really hard! If you'd like to discuss anything during lab (like the duplicate files), please let me know. :) 

Please review and close.

**Comment by al-the-x** [comment]
Please review and close...
