### ISSUE TITLE
05--Matt Oliverio Shavers-of-the-Yak

### ISSUE THREAD

**Issue by ironyarder77** [TIY-Durham/2015-FALL-FEE#125]
**Yak-Shaving**
- Create a new _WIP Issue_ named `05 -- YOUR NAME` with:
  - [x] link to PR in `USERNAME.github.io` from `journal-week-1` into `master`
  - [x] link to PR in `StudentRoster` from `USERNAME:master` into `TIY-Durham:master`
  - [x] link to PR in `TIY-Assignments` from `05--lost-yak` into `master`
-  Create the following _WIP Branch_ in:
  - `USERNAME.github.io` named `journal-week-1`
  - `TIY-Assignments` named `05--lost-yak`
- Create or update the following _WIP Files_ in:
  - `USERNAME.github.io`:
    - `journal-week-1.md`
  - `TIY-Assignments`
    - `ReadingJavaScript/README.md`
    - `NestedAccordion/` from Blueprints
    - `ViewModeSwitch/` from Blueprints
    - `MultiColumnForm/` from Blueprints
    - `TodoMVC/` from Project Template
  - **Journal, Week 1**
  - [x] created branch in `USERNAME.github.io` named `journal-week-1`
  - [x] created new file named `journal-week-1.md`
  - [x] commited, pushed, and opened PR to `master`
  - [x] added draft journal entry
  - **Reading JavaScript: DOM EDITION**
  - [x] the `Window` object
  - [x] the `Location` object
  - [x] the `Document` object
  - [x] the `HTMLElement` type
  - [x] the `HTMLCollection` and `NodeList` types
  - **Making Blueprints**
- [x] Created branch in `TIY-Assignments` named `05--lost-yak`
- [x] Downloaded starter code (ZIP) for:
  - [x] Nested Accordion
  - [x] View Mode Switch
  - [x] Responsive Multi-Column Form
- [x] Extracted starter code into folders:
  - [x] `NestedAccordion`
  - [x] `ViewModeSwitch`
  - [x] `MultiColumnForm`
- [x] **BEAST MODE** -- Working code as-is!
  - **GitHub-ing to Know You**
- [x] merged upstream additions from `TIY-Durham/Student-Roster:master`
- [x] updated your classmate's Markdown file and opened a PR to merge
- [x] thumbs up (:+1:) on your PR from your "Special Someone"
  - **Hello, TodoMVC!**
- [x] Downloaded the [TodoMVC template](https://github.com/tastejs/todomvc-app-template) from GitHub (see instructions!)
- [x] Unzipped into `TIY-Assignments` as `TodoMVC`
- [x] Committed and pushed to _WIP Branch_
- **BEAST MODE**
  - [ ] Followed the instructions in `README.md`
  - [ ] Well, it looks right... Does nothing!
  - **API Gymnastics**
- **Yak Shaving**
  - [x] Create your _WIP Branch_! Maybe even check it out?
  - [x] Create a folder named `APIGymnastics`
  - [x] Copy-pasta **Starting Point** in `APIGymnastics/Etsy.js`
  - [ ] Hey, what about that data?
  - [ ] Seems like a good time to commit and push...
  - [ ] Y'know, why not open a PR, too?
- **So many questions...**
  - [ ] What is the total number of items?
  - [ ] What is the average price of all the items?
  - [ ] What items cost between $14 and $18 dollars? What are their names?
  - [ ] What is the name and price of the only item with a `GBP` currency code?
  - [ ] What are the names of all the items made of wood?
  - [ ] What are the names of the items that are made of 8 or more materials?
  - [ ] How many items were made by their sellers?

**Comment by ironyarder77** [comment]
PR Profile Edit
https://github.com/TIY-Durham/StudentRoster/pull/26

**Comment by ironyarder77** [comment]
!!!THIS is as close as I've come to checking all my assignment boxes.  I wanted to finish but I hit a little wall or a big wall and basically ran out of time.
I could finish this though since I DO know WHAT we are doing..AND I DONT need to know why lol but
I need to feel more comfortable opening up code and running my tests;  I don't think I have a fluid way of executing this..
FIGURE THIS OUT MATT

**Comment by ironyarder77** [comment]
not sure if I should make a PR for this(?)

**Comment by kellymurray** [comment]
Always make a PR! I have to give you an incomplete today because you didn't link your work except the StudentRoster. :(

**Comment by al-the-x** [comment]
Please review and close...

**Comment by ironyarder77** [comment]
Aaaagghhh !!! Oy 
Darn it -I thought I understood what I wasn't doing before- ok I'll make sure I get this TODAY!
Thank you Kelly!
Matt
