### ISSUE TITLE
05 -- Emily Pakes

### ISSUE THREAD

**Issue by kellymurray** [TIY-Durham/2015-FALL-FEE#135]
Incomplete given because:
- No homework submitted.

**Comment by al-the-x** [comment]
Please review and close...

**Comment by ghost** [comment]
https://github.com/pakesybot/TIY-Assignments/issues/7
^This is my open issue. Are we looking at the same thing?

**Comment by kellymurray** [comment]
@pakesybot you put the issue on your own repo and not ours :) Please do that so I can grade it.

**Comment by ghost** [comment]
Gotcha! Please see the copied and pasted one below, now in the correct repo. :)
https://github.com/TIY-Durham/2015-FALL-FEE/issues/137
