### ISSUE TITLE
06-- Emily Pakes

### ISSUE THREAD

**Issue by ghost** [TIY-Durham/2015-FALL-FEE#136]
- **Yak Shaving**
  - [x] Create a new _WIP Issue_ named `06 -- YOUR NAME` with:
    - [x] link to your PR in `USERNAME.github.io` from `journal-week-1` into `master`
    - [x] link to your PR in `TIY-Assignments` from `06--temple-of-dom` into `master`
  - [x] Create a new _WIP Branch_ in:
    - [x] `TIY-Assignments` named `06--temple-of-dom` from `master`... MERGE YOUR 05 PR FIRST!
  - [x] Create or update the following _WIP Files_ in:
    - [x] `USERNAME.github.io`:
      - [x] `journal-week-1.md`
    - [x] `TIY-Assignments`:
      - [x] `NestedAccordion/`
        - [x] `js/scripts.js` -- for _your_ work
        - [x] `index.html` -- removing JavaScript
      - [x] `ViewModeSwitch/`
        - [x] `js/scripts.js` -- for _your_ work
        - [x] `index.html` -- removing JavaScript
      - [x] `MultiColumnForm/`
        - [x] `js/scripts.js` -- nothing yet!
        - [x] `index.html` -- linking `scripts.js`
- **Journal, Week 1**
  - [x] Finished journal entry
  - [x] Had 2 people review it
  - [x] Reviewed some drafts and left comments!
- **Following the Blueprints**
  - *\* Nested Accordion**
    - [x] Clean house: Deleted that JavaScript!
    - [x] Created and linked `scripts.js` in `index.html`
    - [x] Can you say that again in English?
    - [x] What DOM things will we need for that?
    - [x] **BEAST MODE** -- First `NestedAccordion` is accordion-ey...
    - [x] **NIGHTMARE MODE** -- Momma's got a squeezebox! It goes in and out...
  - **View Mode Switch**
    - [x] Clean house: Deleted that JavaScript!
    - [x] Created and linked `scripts.js` in `index.html`
    - [x] What's up with that switch?
    - [x] Can you say that in English this time?
    - [x] What DOM things will we need for that?
    - [x] **NIGHTMARE MODE** -- It's ALIVE! It's ALIVE!

**Comment by ghost** [comment]
PR in USERNAME.github.io from journal-week-1 into master
https://github.com/pakesybot/TIY-Assignments/pull/8

**Comment by ghost** [comment]
PR in TIY-Assignments from 06--temple-of-dom into master
https://github.com/pakesybot/TIY-Assignments/pull/9

**Comment by ghost** [comment]
Create a new WIP Branch in:
TIY-Assignments named 06--temple-of-dom from master:
https://github.com/pakesybot/TIY-Assignments/tree/06--temple-of-dom
Merge 05:
https://github.com/pakesybot/TIY-Assignments/pull/8

**Comment by ghost** [comment]
Updated Journal Entry
https://github.com/pakesybot/pakesybot.github.io/blob/journal-week-1/journal-week-1.md

Two People Reviewed my Entry:
https://github.com/pakesybot/pakesybot.github.io/pull/2#issuecomment-139022640
https://github.com/pakesybot/TIY-Assignments/pull/8#issuecomment-139016912

Reviewed Journal Entries and Left Comments:
https://github.com/jeffworley/jeffworley.github.io/commit/4df24219ab7e4fec134ad28393ea755dd0b01260
https://github.com/jeremyrist/jeremyrist.github.io/commit/66a5525455d02921e8625e455cd73010744772c7

**Comment by ghost** [comment]
journal-week-1 in proper repo and branch PR:
https://github.com/pakesybot/pakesybot.github.io/pull/2

**Comment by ghost** [comment]
I've pushed NestedAccordian and ViewModeSwitch, according to the directions in the Temple of DOM README.  My explanations "in English" are found in the scripts.js files as comments.

**Comment by kellymurray** [comment]
@pakesybot where's your filled out `scripts.js` files? I can't find them in these PRs. Did you push them to another branch?

**Comment by ghost** [comment]
@kellymurray They're in my pushed files for NestedAccordian and ViewModeSwitch. I know I pushed them...lemme see if I can find them on the GitHub! Alternately, I could copy and paste those in here...

**Comment by kellymurray** [comment]
@pakesybot It is better for you to put the comments in the `scripts.js` file in your repos.

**Comment by ghost** [comment]
@kellymurray I thought I did. :-/

**Comment by kellymurray** [comment]
@pakesybot I have to give you an incomplete unless you can show me where it was uploaded to the branch. :(

**Comment by ghost** [comment]
@kellymurray You said you could show me during lab time. Can I copy and paste that info from my Atom file into the files Script.js on GitHub? I completed this assignment, so I have to disagree with the Incomplete label, as it currently stands.

**Comment by al-the-x** [comment]
Please review and close...
