### ISSUE TITLE
00 -- KARLO ELEUTERIO

### ISSUE THREAD

**Issue by karjac14** [TIY-Durham/2015-FALL-FEE#15]
- [x] **GitHub-ing to Know You**
  - [x] [Create a GitHub account]
  - [x] [Edit your GitHub profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so we can recognize your face.
  - [x] Your full name, so we can recognize your name.
  - [x] A valid public email address, so we can contact you.
  - [x] Find and star [the class project](https://github.com/TIY-Durham/2015-FALL-FEE)
  - [x] Read [the Home page on the class wiki](https://github.com/TIY-Durham/2015-FALL-FEE/wiki)
- [x] **You've Got Issues**
  - [x] [Create a new _WIP Issue_](https://github.com/TIY-Durham/2015-FALL-FEE/issues/new)
  - [x] Name it `00 -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] Make this checklist the description
  - [x] Start checking off boxes... :astonished:
- [x] **Send all my GitHub to you...**
  - [x] Learn all you can about `git` and GitHub!
    - Treehouse has [a Git Basics course](http://teamtreehouse.com/library/git-basics)
  - CodeSchool has [a `git` path](https://www.codeschool.com/paths/git)
    - [x] Complete: [Try Git](http://try.github.com)
  - [x] GitHub has a couple of Guides:
    - [x] [Hello World](https://guides.github.com/activities/hello-world/)
    - [x] [Forking Projects](https://guides.github.com/activities/forking/)
  - [x] Add a link to your `Hello-World` and `Fork-and-Spoon` repos as a comment on your _WIP Issue_
- [ ] **Command Line Training**
  - [x] Read: http://eddywashere.com/blog/an-intro-to-the-os-x-command-line/
  - [x] Complete: https://www.codecademy.com/courses/learn-the-command-line/
  - [ ] **BEAST MODE** http://cli.learncodethehardway.org/book/
- [x] **INSTALL ALL THE THINGS!**
  - [x] [Install Homebrew](http://brew.sh) on your Mac
  - [x] Open `Terminal.app`; Don't Panic.
  - [x] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [x] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
  - [x] Using the `brew` command, install the following packages:
    - [x] `zsh`
  - [x] `git`
  - [x] `hub`
  - [x] `node`
  - [x] Add the output of the following commands as comments on your _WIP Issue_:
    - [x] `which zsh && zsh --version`
    - [x] `which git && git --version`
    - [x] `which hub && hub --version`
    - [x] `which node && node --version`
  - [x] Install the following (bonus if you use `brew`):
    - [x] [Google Chrome](http://google.com/chrome)
    - [x] [Atom](http://atom.io)
    - [x] [Dash](http://kapeli.com/dash)
    - [x] [Slack](http://www.slack.com)
    - [x] [SourceTree](https://www.sourcetreeapp.com/)
- [x] **Prezto Change-oh!**
  - [x] Find and _fork_ the Prezto project on GitHub
  - [x] Clone _your fork_ of Prezto into your home directory
  - [x] Follow the installation instructions in the `README.md` file
- [x] **Take a Moment to Reflect**
  - [x] Answered question 1 in a comment on your WIP Issue.
  - [x] Answered question 2 in a comment on your WIP Issue.

**Comment by karjac14** [comment]
zsh && zsh --version 5.0.8
git && git --version 2.5.1
hub && hub --version 2.2.1
node && node --version 0.12.7

**Comment by karjac14** [comment]
Hello World: https://github.com/karjac14/hello-world
Forking Projects: https://github.com/karjac14/Spoon-Knife

**Comment by karjac14** [comment]
## Reflections

#### 1. What difficulties do you predict that you will encounter during our course? How have you reacted to similar situations in the past? How do you plan on reacting to these situations during the class?

Since this is an intense course, I am seeing that I will be overwhelmed with new informations, to the point I may forget things that I learned _lets say_ from the previous week. In the past, I make some time to review again what I have learned or at least familiarize myself where I can pull these informations again in case i'll be needing those infos/technique. I am also looking forward to get some help from the instructors and fellow students.

#### 2. Which part of the prework did you like the MOST? Which part of the prework did you like the LEAST? If you found any of the prework confusing, please explain.

I remember, I enjoyed doing the HTML and CSS exercises, when I did it last February. And also the  Javascript especially when I seeing things are getting to make sense and able to use different JS methods to come up something more complex app. The least thing I liked is the Github part. I understood the foundation and purpose of the system, but there are some tasks (command codes) that I cannot understand. I just followed the instructions without actually knowing whats going on. I also didn't know what Brew, ZSH and Prezto were, I just know that some library or files were installed in my mac. I guess it is part of the experience of squeezing our brains.

**Comment by kellymurray** [comment]
@karjac14 Please review and close.
