### ISSUE TITLE
07-- Rosa Lopez Sanchez

### ISSUE THREAD

**Issue by rosalsm** [TIY-Durham/2015-FALL-FEE#170]
- **Yak Shaving**
  - Create a new _WIP Issue_ named `07 -- YOUR NAME` with:
    - [x] link to your PR in `TIY-Assignments` from `07--the-last-cascade` into `master`
- **Reading JavaScript: Events**
  - [x] How does an `Event` "bubble"? Can I make it stop?
  - [x] What does the `target` property of an `Event` refer to?
  - [x] Besides `click`, what _other_ event types can I trigger with my mouse?
  - [x] What types of events can be triggered on a `<form>` element?
  - [x] `click` me, baby, one more time!
  - [x] `scroll` down the avenue
  - [x] `change` is a-comin'
  - [x] `submit` to mah authah-ri-tah!
  - [x] this is a complete `load`...
  - [x] well, just `unload` about it.
  - [ ] **BEAST MODE** dat keyboard, tho
- **Building the Blueprints**
  - `NestedAccordions` can...
    - [x] First accordion opens when closed... It's a start!
    - [ ] First accordion closes when open... It's a finish?
    - [ ] First accordion opens _and_ closes! It's a wrap! :shipit:
    - [ ] Top-level accordions can open and close... :astonished:
    - [ ] **BEAST MODE** Accordion ALL THE THINGS!
  - `ViewModeSwitch` can...
    - **Always start with the button...**
      - [x] TRACER BULLETS: Houston, we are clear for clicking...
      - [ ] Clicking switches the `"active"` button...
    - **Welcome to the Grid, User...**
      - [ ] TRACER BULLETS: What is changing? Can you change that?
      - [ ] Now make a _Function_ that does that...
    - **Wiring up the clicks...**
      - [ ] Click to switch the grid layout to a list...
      - [ ] Click to switch the list layout to a grid...
  - `MultiColumnForm` can...
    - **Who are you listening to?**
      - [x] TRACER BULLETS: I can see the `target`...
      - [ ] It's not the `<button>`, BTW.
      - [ ] Ready for the main `Event`!
    - **Where is the data?**
      - [ ] Capture the form submission with JavaScript
      - [ ] Then output the form data to the console
    - [ ] Post the output to a comment in your _WIP Issue_

**Comment by rosalsm** [comment]
https://github.com/rosalsm/TIY-Assignments/pull/7

**Comment by kellymurray** [comment]
Received Continue Improving because:
- You attempted everything - yay! But it looks like you didn't really complete anything. Did you get stuck?

**Comment by al-the-x** [comment]
Please review and close...
