### ISSUE TITLE
17 -- Eric Baiden Quayson

### ISSUE THREAD

**Issue by ericquayson** [TIY-Durham/2015-FALL-FEE#331]
- **Yak-Shaving**
  - [x] Create a _WIP Issue_ in the class repo
  - [x] **MERGE ALL YOUR OPEN PRs!**
    - [x] Specifically `TIY-GitHub:yak-shaving` into `master`!
  - [x] Create a _WIP Branch_ in:
    - [x] `TIY-Assignments` named `17--beneath-the-APIs` from `master`
    - [x] `TIY-GitHub` named `release--0.0.1` from `master`
- [ ] Create or update the following _WIP Files_ in:
  - `USERNAME.GitHub.io:journal-week-4`
    - `journal-week-4.md` or something creative
    - `tutorial-week-4.md` or something creative
  - `TIY-Assignments:17--beneath-the-APIs`
    - `CheatSheets/GitHubAPI.md`
  - `TIY-GitHub:release--0.0.1`
    - `specs/octocat--details.png`
    - `src/`
      - `scss/custom.scss`
      - `js/main.js`
      - `index.html`
- [ ] Add comments to your _WIP Issue_ with links to your PRs in:
  - [x] `USERNAME.GitHub.io` from `journal-week-4` into `master`
  - [x] `TIY-Assignments` from `17--beneath-the-APIs` into `master`
  - `TIY-GitHub`
    - [x] from `release--0.0.1` into `master`
    - [x] from `feature--basic-layout` into `release--0.0.1` (MERGED)
    - [ ] from `feature--profile-details` into `release--0.0.1` (MERGED)
    - [ ] from `feature--fetching-data` into `release--0.0.1` (MERGED)
- **Journal, Week 4**
  - [ ] Outline for _reflective_!
  - [ ] Outline for _tutorial_!
  - [ ] Peer review x2!
  - [ ] Reviewed peers x2!
- **Reading APIs**
  - What are the endpoints for fetching...
    - the profile data for a user?
    - the organizations a user belongs to?
    - the repositories a user has created?
    - a filtered list of repositories?
    - a sorted list of repositories?
    - public events for a user?
  - When fetching public events for a user...
    - How many results are returned by default?
    - What limitations exist on fetching _more_ results?
    - What is the basic structure of the results?
    - What fields are included in each result?
    - What are the data types for each field?
    - What are some of the different values for the `type` field?
- **GitHub Revolution, Part 2**
  - [ ] `feature--basic-layout`
  - [ ] `feature--profile-details`
  - [ ] `feature--fetching-data`

**Comment by ericquayson** [comment]
PR - feature--basic-layout https://github.com/ericquayson/TIY-GitHub/pull/2

**Comment by ericquayson** [comment]
PR - feature--profile-details  https://github.com/ericquayson/TIY-GitHub/pull/4

**Comment by kellymurray** [comment]
Incomplete given because:
- Missing assignments

I know you mentioned there was a merge conflict that blocked you. Please chat with David or me during lab hours and we'll see what the problem is.

**Comment by al-the-x** [comment]
Please review and close...
