### ISSUE TITLE
HALFTIME -- Terry Calhoun

### ISSUE THREAD

**Issue by drumslayert** [TIY-Durham/2015-FALL-FEE#414]
- [x] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME`
    - link to PRs in `USERNAME.github.io`
    - link to PRs in `TIY-Assignments`
  - _WIP Branch_:
    - `USERNAME.github.io`
      - `journal-week-5`
      - `release-0.0.2` from `master`
      - `feature--remodeling` from `release--0.0.2`
      - `feature--*` from `release--0.0.2`
    - `TIY-Assignments`
      - `release--0.0.0` from `master`
      - `feature--yak-shaving` from `release--0.0.0`
      - `feature--*` from `release--0.0.1`
  - _WIP Files_:
    - `USERNAME.github.io:release--0.0.2`
      - `_drafts/` -- for any WIP files...
      - `_posts/` -- your completed posts
      - `src/`
        - `scss/*.scss`
        - `js/*.js`
        - `index.html`
      - `bower.json`
      - `package.json`
    - `TIY-Assignments:release--0.0.1`
      - `DropDownMenu` / `SlideOutMenu` / `ResponsiveIcons` / `ResponsiveGrid` -- starting with `yo h5bp`
        - `scss/`
          - `main.scss`
          - `_grid.scss`
          - `_FEATURE.scss` -- where `FEATURE` is a feature name
        - `specs/` -- with Skitches, of course!
        - `.gitignore` -- ignoring ALL THE THINGS!
        - `bower.json` -- from `bower init` and `bower install`
        - `package.json` -- from `npm init` and `npm install`
        - `index.html` -- with links to all the `bower`-installed packages
- **HALFTIME Journal**
  - [ ] **Three's Company**
  - [ ] **Build It Out**
  - [ ] **Time for some remodeling!**
- **Blueprints Everywhere!**
  - [x] Yaks Shaved
  - [x] Some MFing HTML & SCSS
  - **BEAST MODE** - MORE BLUEPRINTS!

**Comment by drumslayert** [comment]
- `TIY-Assignments:release--0.0.0`
  - [x] `SlideOutMenu` -- starting with `yo h5bp`
    - [x] `scss/`
      - [x] `main.scss`
      - [x] `_grid.scss`
      - [x] `_FEATURE.scss` -- where `FEATURE` is a feature name
    - [x] `specs/` -- with Skitches, of course!
    - [x] `.gitignore` -- ignoring ALL THE THINGS!
    - [x] `bower.json` -- from `bower init` and `bower install`
    - [x] `package.json` -- from `npm init` and `npm install`
    - [x] `index.html` -- with links to all the `bower`-installed packages

PR: feature-yak-shaving  https://github.com/drumslayert/TIY-Assignments/pull/21
PR: feature-skitch  https://github.com/drumslayert/TIY-Assignments/pull/25
PR: feature--basic-layout  https://github.com/drumslayert/TIY-Assignments/pull/27

**Comment by drumslayert** [comment]
- `TIY-Assignments:release--0.0.0`
  - [x] `ResponsiveGrid` -- starting with `yo h5bp`
    - [x] `scss/`
      - [x] `main.scss`
      - [x] `_grid.scss`
      - [x] `_FEATURE.scss` -- where `FEATURE` is a feature name
    - [x] `specs/` -- with Skitches, of course!
    - [x] `.gitignore` -- ignoring ALL THE THINGS!
    - [x] `bower.json` -- from `bower init` and `bower install`
    - [x] `package.json` -- from `npm init` and `npm install`
    - [x] `index.html` -- with links to all the `bower`-installed package

Responsive grid PR: https://github.com/drumslayert/TIY-Assignments/pull/22

**Comment by drumslayert** [comment]
PR for journal and resource:   https://github.com/drumslayert/drumslayert.github.io/pull/25
PR from release-0.0.0 to master: https://github.com/drumslayert/TIY-Assignments/pull/26
Accidentally updated my resource in mater: https://github.com/drumslayert/drumslayert.github.io/blob/master/resource-week-5.md

**Comment by drumslayert** [comment]
PR: feature--basic-layout to release-0.0.1: https://github.com/drumslayert/TIY-Assignments/pull/27
PR: feature--complete-layout to release-0.0.1: https://github.com/drumslayert/TIY-Assignments/pull/29
Additional PR: feature--complete-layout to release-0.0.1: 
https://github.com/drumslayert/TIY-Assignments/pull/30

PR: release--0.0.1 to master: https://github.com/drumslayert/TIY-Assignments/pull/31

**Comment by drumslayert** [comment]
PR: feature--header-final to release-0.0.2: https://github.com/drumslayert/TIY-Assignments/pull/32
PR: feature--main-final to release-0.0.2: https://github.com/drumslayert/TIY-Assignments/pull/33

PR: release--0.0.2 to master: https://github.com/drumslayert/TIY-Assignments/pull/34

**Comment by kellymurray** [comment]
Continue Improving given because:
- Looks like you worked hard on everything, but got a little stuck on Slide Out Menu. Did the in-class feedback help?

**Comment by al-the-x** [comment]
Please review and close...
