### ISSUE TITLE
HALFTIME -- Eric Baiden - Quayson 

### ISSUE THREAD

**Issue by ericquayson** [TIY-Durham/2015-FALL-FEE#415]
- [x] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME`
    - link to PRs in `USERNAME.github.io`
    - link to PRs in `TIY-Assignments`
  - _WIP Branch_:
    - `USERNAME.github.io`
      - `journal-week-5`
      - `release-0.0.2` from `master`
      - `feature--remodeling` from `release--0.0.2`
      - `feature--*` from `release--0.0.2`
    - `TIY-Assignments`
      - `release--0.0.0` from `master`
      - `feature--yak-shaving` from `release--0.0.0`
      - `feature--*` from `release--0.0.1`
  - _WIP Files_:
    - `USERNAME.github.io:release--0.0.2`
      - `_drafts/` -- for any WIP files...
      - `_posts/` -- your completed posts
      - `src/`
        - `scss/*.scss`
        - `js/*.js`
        - `index.html`
      - `bower.json`
      - `package.json`
    - `TIY-Assignments:release--0.0.1`
      - `DropDownMenu` / `SlideOutMenu` / `ResponsiveIcons` / `ResponsiveGrid` -- starting with `yo h5bp`
        - `scss/`
          - `main.scss`
          - `_grid.scss`
          - `_FEATURE.scss` -- where `FEATURE` is a feature name
        - `specs/` -- with Skitches, of course!
        - `.gitignore` -- ignoring ALL THE THINGS!
        - `bower.json` -- from `bower init` and `bower install`
        - `package.json` -- from `npm init` and `npm install`
        - `index.html` -- with links to all the `bower`-installed packages
- **HALFTIME Journal**
  - [x] **Three's Company**
  - [x] **Build It Out**
  - [x] **Time for some remodeling!**
- **Blueprints Everywhere!**
  - [x] Yaks Shaved
  - [x] Some MFing HTML & SCSS
  - **BEAST MODE** - MORE BLUEPRINTS!

**Comment by ericquayson** [comment]
Feature--remodeling -- https://github.com/ericquayson/ericquayson.github.io/pull/20

**Comment by ericquayson** [comment]
release 0.0.2 -- https://github.com/ericquayson/ericquayson.github.io/pull/21

**Comment by ericquayson** [comment]
unfortunate p.r dropdown menu -- https://github.com/ericquayson/TIY-Assignments/pull/28

**Comment by ericquayson** [comment]
Journal, Tutorials, resource and conflict issues - YAY! :( https://github.com/ericquayson/ericquayson.github.io/pull/15

**Comment by ericquayson** [comment]
release 0.0.3 -- https://github.com/ericquayson/ericquayson.github.io/pull/22

**Comment by ericquayson** [comment]
TIY-Assignment -- https://github.com/ericquayson/TIY-Assignments/pull/35

**Comment by kellymurray** [comment]
Continue Improving given because:
- Looks like you touched everything but didn't quite get through the Blueprints, especially the Dollar Menu assignment. Let's get that assessment on the books! Reach out to David and schedule a time (or I can help you reach out to him).
