### ISSUE TITLE
HALFTIME -- Jasmine Baik

### ISSUE THREAD

**Issue by boshnivolo** [TIY-Durham/2015-FALL-FEE#416]
- [x] **Yak Shaving**
  - [x] _WIP Issue_: `HALFTIME -- YOUR NAME`
    - [x] link to PRs in `USERNAME.github.io`
    - [x] link to PRs in `TIY-Assignments`
  - [x] _WIP Branch_:
    - [x] `USERNAME.github.io`
      - [x] `journal-week-5`
      - [x] `release-0.0.2` from `master`
      - [x] `feature--remodeling` from `release--0.0.2`
      - [x] `feature--*` from `release--0.0.2`
    - [x] `TIY-Assignments`
      - [x] `release--0.0.0` from `master`
      - [x] `feature--yak-shaving` from `release--0.0.0`
      - [x] `feature--*` from `release--0.0.1`
  - [x] _WIP Files_:
    - [x] `USERNAME.github.io:release--0.0.2`
      - [x] `_drafts/` -- for any WIP files...
      - [x] `_posts/` -- your completed posts
      - [x] `src/`
        - [x] `scss/*.scss`
        - [x] `js/*.js`
        - [x] `index.html`
      - [x] `bower.json`
      - [x] `package.json`
    - [x] `TIY-Assignments:release--0.0.1`
      - [x] `DropDownMenu` / `SlideOutMenu` / `ResponsiveIcons` / `ResponsiveGrid` -- starting with `yo h5bp`
        - [x] `scss/`
          - [x] `main.scss`
          - [x] `_grid.scss`
          - [x] `_FEATURE.scss` -- where `FEATURE` is a feature name
        - [x] `specs/` -- with Skitches, of course!
        - [x] `.gitignore` -- ignoring ALL THE THINGS!
        - [x] `bower.json` -- from `bower init` and `bower install`
        - [x] `package.json` -- from `npm init` and `npm install`
        - [x] `index.html` -- with links to all the `bower`-installed packages
- **HALFTIME Journal**
  - [x] **Three's Company**
  - [x] **Build It Out**
  - [x] **Time for some remodeling!**
- **Blueprints Everywhere!**
  - [x] Yaks Shaved
  - [x] Some MFing HTML & SCSS
  - **BEAST MODE** - MORE BLUEPRINTS!

**Comment by boshnivolo** [comment]
<strong>Journal PR</strong>: https://github.com/boshnivolo/boshnivolo.github.io/pull/17
- <strong>Jon's Week 5</strong>: https://github.com/jmcreasman/jmcreasman.github.io/pull/12
- <strong>Lacey's Week 5</strong>: https://github.com/Ricecoder/ricecoder.github.io/pull/24

<strong>release--0.0.2</strong>: https://github.com/boshnivolo/boshnivolo.github.io/pull/19
- _I accidentally committed changes directly to the release--0.0.2 branch instead of the feature--remodeling...so the work is there, but there's no side branch.

<strong>TIY-Assessments release--0.0.0 PR</strong>: https://github.com/boshnivolo/TIY-Assignments/pull/25
<strong>TIY-Assessments release--0.0.1 PR</strong>: https://github.com/boshnivolo/TIY-Assignments/pull/26
<strong>TIY-Assessments release--0.0.2 PR</strong>: https://github.com/boshnivolo/TIY-Assignments/pull/28

**Comment by kellymurray** [comment]
Continue Improving given because:
- Looks like you touched everything, and made substantial progress on the Blueprints, but didn't get far on the blog design.

**Comment by al-the-x** [comment]
Please review and close...
