### ISSUE TITLE
HALFTIME -- J.R. Worley

### ISSUE THREAD

**Issue by jeffworley** [TIY-Durham/2015-FALL-FEE#420]
- [x] **Yak Shaving**
  - [x] _WIP Issue_: `HALFTIME -- YOUR NAME`
    - [x] link to PRs in `USERNAME.github.io`
    - [x] link to PRs in `TIY-Assignments`
  - [x] _WIP Branch_:
    - [x] `USERNAME.github.io`
      - [x] `journal-week-5`
      - [x] `release-0.0.2` from `master`
      - [x] `feature--remodeling` from `release--0.0.2`
      - [x] `feature--*` from `release--0.0.2`
    - [x] `TIY-Assignments`
      - [x] `release--0.0.0` from `master`
      - [x] `feature--yak-shaving` from `release--0.0.0`
      - [x] `feature--*` from `release--0.0.1`
  - [x] _WIP Files_:
    - [x] `USERNAME.github.io:release--0.0.2`
      - [x] `_drafts/` -- for any WIP files...
      - [x] `_posts/` -- your completed posts
      - [x] `src/`
        - [x] `scss/*.scss`
        - [x] `js/*.js`
        - [x] `index.html`
      - [x] `bower.json`
      - [x] `package.json`
    - [x] `TIY-Assignments:release--0.0.1`
      - [x] `DropDownMenu` / `SlideOutMenu` / `ResponsiveIcons` / `ResponsiveGrid` -- starting with `yo h5bp`
        - [x] `scss/`
          - [x] `main.scss`
          - [x] `_grid.scss`
          - [x] `_FEATURE.scss` -- where `FEATURE` is a feature name
        - [x] `specs/` -- with Skitches, of course!
        - [x] `.gitignore` -- ignoring ALL THE THINGS!
        - [x] `bower.json` -- from `bower init` and `bower install`
        - [x] `package.json` -- from `npm init` and `npm install`
        - [x] `index.html` -- with links to all the `bower`-installed packages
- [x] **HALFTIME Journal**
  - [x] **Three's Company**
  - [x] **Build It Out**
  - [x] **Time for some remodeling!**
- [x] **Blueprints Everywhere!**
  - [x] Yaks Shaved
  - [x] Some MFing HTML & SCSS
  - [ ] **BEAST MODE** - MORE BLUEPRINTS!
#### Three's Company

How're those drafts going? Get a final draft done for your reflection and resource entries, then keep working on your tutorial. Make sure you get those 2 :+1:s and give 2 :+1:s!
#### Build It Out

Not really a _writing_ assignment, per se... Let's make that `USERNAME.github.io` repo into a _real_ blog site. We'll have to do a little remodeling, and you're gonna need some paint. First, _merge your existing PRs_ and remember to _bump the version number_ in `release--0.0.1` before merging to `master`!

Before you get going, _make your own checklist_ describing the Features you're going to build to make your template come to life. Wait, what's a Feature? Glad you asked!

> A Feature is a complete and distinct piece of the functionality or experience of a piece of software. The smallest, indivisible part of an interaction is a Feature.

In the terms of any web-based interface, a Feature _definitely_ includes HTML and CSS and _usually_ involves JavaScript. In terms of a _responsive_ website, any Feature _also_ requires Media Queries, since each _component_ -- [Brad Frost's "organisms" in "Atomic Design"](http://bradfrost.com/blog/post/atomic-web-design/#oorganisms) -- probably has responsive behavior. _Don't leave your MQs until the end unless you want to cry!_ :cry:

Each feature that you identify has some Baby Steps to build it: MF'g HTML, basic layout, responsive-ness, interactivity. Break each down into its own checklist and record them in your _WIP Issue_. Lord knows you've had some examples to work from.
#### Time for some remodeling!

Create a new branch called `release--0.0.2` from `master`. Check out that branch, and create a `feature--remodeling` branch based on it to do this initial work in. _Commit after every step!_
1. Move all your old journal entries and tutorials into a new directory called `_posts/`; stick your in-progress journal entries and "parking lot" in `_drafts/`.
2. Use your `init` commands to create `bower.json` and `package.json` files if you haven't already.
3. Use `bower` to upgrade the versions of `jquery`, `modernizr`, and `normalize.css`... don't forget to replace the links in `index.html`!
4. Add a `start` task to `package.json` that runs `browser-sync` and opens your `src/index.html` file.

Push your branch to GitHub and open a PR into `release--0.0.2` for review. _Please review each other's work carefully!_ Making a mistake at this point may derail you for a while... Merge your approved PR and update your local `release--0.0.2` branch.
#### To the feature lists!

Now that you've got _those_ yaks shaved, it's time to start on the _real_ build-out. Pick one of the Features you planned -- the navigation bar, one of the post blocks, the sidebar or even a _part_ of the sidebar -- and create a branch based on `release-0.0.2` called `feature--FEATURE-NAME` where `FEATURE-NAME` describes the part you're working on, e.g. `feature--sidebar-profile` or `feature--main-column`. Commit _something_ -- a comment declaring intent -- into that branch and push it to GitHub so you can open a PR.

Open a PR into `release-0.0.2` named after that Feature and paste the checklist for that Feature into the description. Check the items off as you work, and commit _often_ using [descriptive, imperative commit messages](http://chris.beams.io/posts/git-commit/). If you're committing a horde of files or a wall of changes at once, you're doing it wrong. Read up on and try using `git add --patch` and `git add --interactive` to make your commits smaller, even when you've edited a ton of different things.

When you finish your feature and complete your checklist, solicit peer review of your work and merge it. If you complete your checklist _before_ you finish your feature, try adding those invisible items to your checklist. If you get stuck on a part of a feature, work on another one. Don't be afraid of having multiple feature branches open at once; you'll regularly have multiple "in-progress" branches while working on a team.
### Blueprints Everywhere!

You've met four of the Blueprints so far: `MultiColumnForm`, `NestedAccordion`, `VerticalTimeline`, and  `ViewModeSwitch`. But there's others out there, too, and it's time to tackle them -- in pairs.

You've been (mostly) randomly assigned a partner from the class to work with through the weekend. You and your partner will work together to build all four of the following layouts, but each of you is only responsible for one layout from each category.
##### Dollar (`$`) Menu
- [Horizontal Drop-Down Menu](http://tympanus.net/codrops/2013/03/05/horizontal-drop-down-menu/)
- [Horizontal Slide-Out Menu](http://tympanus.net/codrops/2013/05/17/horizontal-slide-out-menu/)
##### McGriddles
- [Responsive Icon Grid](http://tympanus.net/codrops/2013/07/01/responsive-icon-grid/)
- [Responsive Full Width Grid](http://tympanus.net/codrops/2013/04/17/responsive-full-width-grid/)

If one partner chooses the **Horizontal Drop-Down Menu** and **Responsive Full-Width Grid**, the other partner gets **Horizontal Slide-Out Menu** and **Responsive Icon Grid**. You each get _one from each category_... got it? Stay with your partner; the two layouts are similar enough that you'll have more success working together than apart.

Write your plan down for each project in your _WIP Issue_ that includes yak shaving and a list of features. Make checklists. Put your feature checklists on the PRs for each feature branch as you proceed.

Tonight, craft your plan and get started on both projects, starting with MF'g HTML and some basic layout with Sass. A responsive grid will probably help. Remember to give yourself a container!

Create a branch called `release--0.0.0` in your `TIY-Assignments` repo and get to shaving those yaks. Create folders for your new Blueprints, and start them with `yo h5bp`, `bower init` and `npm init`. Tell `git` to ignore stuff. All those kind of things that we keep doing over and over again. Man, a checklist sure would be nice about now...

After you review that with your partner and merge, get started on a _new_ release -- `release--0.0.1` -- that will contain the first parts of your new Blueprints: MF'g HTML and basic layout, using your grid in SCSS, of course. Create feature branches for those and add your plan to the PR for each. Merge when you have shown your _working code_ to your partner.
#### BEAST MODE

If you need a head start on tomorrow, start creating and merging feature branches. Your partner should serve as your second eyes for approving PRs to merge. Move at your own pace, and don't leave your buddy behind!
#### NIGHTMARE MODE

Not enough for you? Then try these on for size, but make sure your partner is on board. You get one, they get one.
- [Quotes Rotator](http://tympanus.net/codrops/2013/03/29/quotes-rotator/)
- [Full Width Image Slider](http://tympanus.net/codrops/2013/02/26/full-width-image-slider/)

You'll need all your skills so far to complete this Blueprint challenge! No one has completed it yet...
- [x] **Yak Shaving**
  - [x] _WIP Issue_: `HALFTIME -- YOUR NAME` -- use the _same_ issue!
    - [x] Add links to PRs in `USERNAME.github.io`:
      - [x] from `journal-week-5` into `master`
      - [x] from `release--0.0.3` into `master`
      - [x] from `feature--*` into `release--0.0.3`
    - [x] Add links to PRs in `TIY-Assignments`:
      - [x] from `release--0.0.2` into `master`
      - [x] from `feature--*` into `release--0.0.2`
  - [x]  _WIP Branch_:
    - [x] `USERNAME.github.io`
      - [x] `journal-week-5`
      - [x] `release-0.0.3` from `master`
      - [x] `feature--*` from `release--0.0.3`
    - [x] `TIY-Assignments`
      - [x] `release--0.0.2` from `master`
      - [x] `feature--*` from `release--0.0.2`
  - [x] _WIP Files_:
    - [x] `USERNAME.github.io:journal-week-5`
      - [x] `journal-week-5.md`
      - [x] `tutorial-week-5.md`
      - [x] `resource-week-5.md`
    - [x] `USERNAME.github.io:release--0.0.3`
      - [x] `src/`
        - [ ] `js/*.js`
        - [x] `scss/*.scss`
        - [x] `index.html`
    - [x] `TIY-Assignments:release--0.0.2`
      - [x] `{DropDownMenu,SlideOutMenu}/`
        - [x] `js/*.js`
        - [x] `scss/*.scss`
        - [x] `index.html`
      - [x] `{ResponsiveIcons,ResponsiveGrid}/`
        - [ ] **BEAST MODE** `js/*.js`
        - [x] `scss/*.scss`
        - [x] `index.html`
- [x] **HALFTIME Journal!**
  - [x] Week 5 Journal was due _today!_
  - [x] Week 5 Tutorial due on _Monday!_
  - [x] Week 5 Resource should _already be done!_
- [x] **Finishing Up the Features**
  - [x] Move on to `release--0.0.3`!
  - [x] Cut the fat! _Just essential features!_
  - [ ] Get Peer Reviews that _include feedback!_
- [x] **Blueprints Everywhere!**
  - [x] Move on to `release--0.0.2`!
  - [ ] Maybe get to `release--0.1.0`...?
  - [ ] What version should you be on by Monday?
  - **BEAST MODE** How about some JavaScript?
### Halftime Journal

Final draft for your tutorial! Make sure you get those 2 :+1:s and give 2 :+1:s!
### Finishing Up the Features

You should be finishing up on your build out in `USERNAME.github.io` so that we can transplant your `_posts/` into your homepage next week. Prioritize features that directly contribute to the functionality of your site and cut any that don't look feasible any more... at least until your Portfolio Week (that's lucky 13).

Make branch `release--0.0.3`. Continue working on your features in `feature--*` branches and merging them as you get reviewed by your peers (2x:+1:s!). _Show your work_ for visual inspection and _insist on seeing their work_, too. Just eyeballing the code isn't good enough...! _Also_ inspect the code for ugly stuff: poor indentation, swathes of commented code, vast tracts of whitespace. Write down your feedback in the PR. Incorporate the feedback of others.
### Blueprints Everywhere!

Keep working with your partner on your Blueprints. Your current release branch should be `release--0.0.2`; open a new one every morning over the weekend. _Don't forget to bump the version!_

When you finish one of your Blueprints, or at least add a significant portion of functionality to it, consider bumping the `minor` version instead of the `patch` version. By the end of the weekend, what should your version number be, at least?
#### BEAST MODE

Those **McGriddles**... Oh, those **McGriddles**. So very tedious. So much repetition. And they don't need _any_ JavaScript at all, do they? Can you _invent_ some? Wouldn't it be nice if JavaScript could do all that repetition for you? Maybe instead of kitty pictures, [you could pull some image data from a web service?](https://api.imgur.com/) Perhaps [fetch some cool icons from The Noun Project?](http://api.thenounproject.com/documentation.html#get--collection-%28int-id%29-icons)

**Comment by jeffworley** [comment]
jeffworley.github.io journal-week-5.md PR:
https://github.com/jeffworley/jeffworley.github.io/pull/26

jeffworley.github.io release-0.0.2 PR:
https://github.com/jeffworley/jeffworley.github.io/pull/28

jeffworley.github.io feature--remodeling PR:
https://github.com/jeffworley/jeffworley.github.io/pull/27

jeffworley.github.io feature--blog-site-header-hamburger-menu PR:
https://github.com/jeffworley/jeffworley.github.io/pull/29

jeffworley.github.io release-0.0.3 PR:
https://github.com/jeffworley/jeffworley.github.io/pull/30

jeffworley.github.io feature--full-entry-on-main PR:
https://github.com/jeffworley/jeffworley.github.io/pull/31

**Comment by jeffworley** [comment]
Overview of Blog Template Recreation Features: (I will include a screenshot of the breakdown for each one as I create branches for it)

<img width="1508" alt="screen shot 2015-10-07 at 11 25 20 pm" src="https://cloud.githubusercontent.com/assets/4316268/10357786/3fbf4892-6d54-11e5-8cdd-cc5d7ab1c0a0.png">

**Comment by jeffworley** [comment]
Trello that Shay and I Set Up to Manage This Project:
https://trello.com/b/wYUEGSht/22-halftime

tiy-assignments release--0.0.0 PR:
https://github.com/jeffworley/tiy-assignments/pull/23

tiy-assignments feature--yak-shaving PR:
https://github.com/jeffworley/tiy-assignments/pull/22

tiy-assignments feature--map-out-html PR:
https://github.com/jeffworley/tiy-assignments/pull/24

tiy-assignments release--0.0.2 PR:
https://github.com/jeffworley/tiy-assignments/pull/27

### DDM:

tiy-assignments feature--initial-page-load-mv PR:
https://github.com/jeffworley/tiy-assignments/pull/26

tiy-assignments feature--product-category-selected-mv PR:
https://github.com/jeffworley/tiy-assignments/pull/28

tiy-assignments feature--downloads-category-selected-mv PR:
https://github.com/jeffworley/tiy-assignments/pull/29

tiy-assignments feature--freeware-category-selected-mv PR:
https://github.com/jeffworley/tiy-assignments/pull/32

tiy-assignments feature--responsive-to-tablet-view PR:
https://github.com/jeffworley/tiy-assignments/pull/33

tiy-assignments feature--responsive-to-desktop-view PR:
https://github.com/jeffworley/tiy-assignments/pull/34

### RIG:

tiy-assignments initial-load-page-mv PR:
https://github.com/jeffworley/tiy-assignments/pull/35

tiy-assignments responsive-to-tablet-view PR:
https://github.com/jeffworley/tiy-assignments/pull/36

**Comment by al-the-x** [comment]
Please review and close...
