### ISSUE TITLE
HALFTIME - Karlo Eleuterio

### ISSUE THREAD

**Issue by karjac14** [TIY-Durham/2015-FALL-FEE#421]
- [x] **Yak Shaving**
  - [x] _WIP Issue_: `HALFTIME -- YOUR NAME`
    - [x] link to PRs in `USERNAME.github.io`
    - [x] link to PRs in `TIY-Assignments`
  - [x] _WIP Branch_:
    - [x] `USERNAME.github.io`
      - [x] `journal-week-5`
      - [x] `release-0.0.2` from `master`
      - [x] `feature--remodeling` from `release--0.0.2`
      - [x] `feature--*` from `release--0.0.2`
    - [x] `TIY-Assignments`
      - [x] `release--0.0.0` from `master`
      - [x] `feature--yak-shaving` from `release--0.0.0`
      - [x] `feature--*` from `release--0.0.1`
  - [x] _WIP Files_:
    - [x] `USERNAME.github.io:release--0.0.2`
      - [x] `_drafts/` -- for any WIP files...
      - [x] `_posts/` -- your completed posts
      - [x] `src/`
        - [x] `scss/*.scss`
        - [x] `js/*.js`
        - [x] `index.html`
      - [x] `bower.json`
      - [x] `package.json`
    - [x] `TIY-Assignments:release--0.0.1`
      - [x] `DropDownMenu` / `SlideOutMenu` / `ResponsiveIcons` / `ResponsiveGrid` -- starting with `yo h5bp`
        - [x] `scss/`
          - [x] `main.scss`
          - [x] `_grid.scss`
          - [x] `_FEATURE.scss` -- where `FEATURE` is a feature name
        - [x] `specs/` -- with Skitches, of course!
        - [x] `.gitignore` -- ignoring ALL THE THINGS!
        - [x] `bower.json` -- from `bower init` and `bower install`
        - [x] `package.json` -- from `npm init` and `npm install`
        - [x] `index.html` -- with links to all the `bower`-installed packages
- **HALFTIME Journal**
  - [x] **Three's Company**
  - [x] **Build It Out**
  - [x] **Time for some remodeling!**
- **Blueprints Everywhere!**
  - [x] Yaks Shaved
  - [x] Some MFing HTML & SCSS
  - **BEAST MODE** - MORE BLUEPRINTS!
###### 
- [x] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME` -- use the _same_ issue!
    - Add links to PRs in `USERNAME.github.io`:
      - from `journal-week-5` into `master`
      - from `release--0.0.3` into `master`
      - from `feature--*` into `release--0.0.3`
    - Add links to PRs in `TIY-Assignments`:
      - from `release--0.0.2` into `master`
      - from `feature--*` into `release--0.0.2`
  -  _WIP Branch_:
    - `USERNAME.github.io`
      - `journal-week-5`
      - `release-0.0.3` from `master`
      - `feature--*` from `release--0.0.3`
    - `TIY-Assignments`
      - `release--0.0.2` from `master`
      - `feature--*` from `release--0.0.2`
  - _WIP Files_:
    - `USERNAME.github.io:journal-week-5`
      - `journal-week-5.md`
      - `tutorial-week-5.md`
      - `resource-week-5.md`
    - `USERNAME.github.io:release--0.0.3`
      - `src/`
        - `js/*.js`
        - `scss/*.scss`
        - `index.html`
    - `TIY-Assignments:release--0.0.2`
      - `{DropDownMenu,SlideOutMenu}/`
        - `js/*.js`
        - `scss/*.scss`
        - `index.html`
      - `{ResponsiveIcons,ResponsiveGrid}/`
        - **BEAST MODE** `js/*.js`
        - `scss/*.scss`
        - `index.html`
- [x] **HALFTIME Journal!**
  - Week 5 Journal was due _today!_
  - Week 5 Tutorial due on _Monday!_
  - Week 5 Resource should _already be done!_
- [ ] **Finishing Up the Features**
  - Move on to `release--0.0.3`!
  - Cut the fat! _Just essential features!_
  - Get Peer Reviews that _include feedback!_
- [x] **Blueprints Everywhere!**
  - Move on to `release--0.0.2`!
  - Maybe get to `release--0.1.0`...?
  - What version should you be on by Monday?
  - **BEAST MODE** How about some JavaScript?

**Comment by karjac14** [comment]
Karlo's Blog
- [x] **Set it up**
  - NPMs:  Browser-Sync, Noded-Sass
  - Bowers: Jquery, Lodash other CSSs
  - Git Ignore
- [x] `feature--layout` Basic Layout
  - HTML`
    - `.container`
    - `sections divs article`
    - `Ipsums`
  - CSS`
    - `.container`
    - `sections divs article`
- [x] `feature--infos` General Information (paragraphs)
- [x] `feature--navs` Navigation Buttons
- [x] `feature--cursor` Blinking Cursor Beside Name

**Comment by karjac14** [comment]
**Checklist for Blueprints:**
- [x] **TIY-Assignments**
  - ​_WIP Branch_​: `feature--yak-shaving` from `release--0.0.0`
    - [x] Create Blueprints
      - [x] `yo h5bp`
      - [x] `bower init`
      - [x] `npm init`
    - [x] Dropdown Menu
    - [x] Slideout Menu
    - [x] Responsive Icons
    - [x] Responsive Full Width Grid
  - ​_WIP Branch_​: `feature--basic-layout` from `release--0.0.1`
    - [x] Karlo
      - [x] Slideout Menu
        - [x] HTML
        - [x] SCSS
    - [x] Responsive Full Width Grid
      - [x] HTML
      - [x] SCSS
  - [x] Camille
    - [x] Dropdown Menu
      - [x] HTML
      - [x] SCSS
    - [x] Responsive Icons
      - [x] HTML
      - [x] SCSS
  - ​_WIP Branch_​: `feature--details-content` from `release--0.0.2`
    - [x] Images
    - [x] text
    - [x] _details.scss
    - [x] MERGE to `release--0.0.2`
  - ​_WIP Branch_​: `feature--responsive-layout` from `release--0.0.2`
    - [x] Media Queries
    - [x] Grid _grid.scss?
    - [x] _responsive.scss
    - [x] MERGE to `release--0.0.2`
    - [x] MERGE `release--0.0.2` to `master`
  - ​_WIP Branch_​: `feature--details-tabs` from `release--0.1.0`
    - [x] Create `release--0.1.0` from `master` 
    - [x] Create `feature--details-tabs` from `release--0.1.0
    - [x] Slideout Menu
      - [x] JavaScript
      - [ ] _tabs.scss
      -  [ ] Responsive?
    - [ ] Dropdown Menu
      - [ ] JavaScript
        - [ ] _tabs.scss
        -  [ ] Responsive?

**Comment by karjac14** [comment]
**Journals PR:**
https://github.com/karjac14/karjac14.github.io/pull/12
Reviews to: Shay & Rosa

0.0.2 Sub-Branch  
remodeling to 0.0.2: https://github.com/karjac14/karjac14.github.io/pull/17
feature-layout to 0.0.2: https://github.com/karjac14/karjac14.github.io/pull/19
0.0.2 to master: https://github.com/karjac14/karjac14.github.io/pull/18

0.0.3 Sub-branch
feature-infos: https://github.com/karjac14/karjac14.github.io/pull/20
feature-navs: https://github.com/karjac14/karjac14.github.io/pull/22
feature-cursor: https://github.com/karjac14/karjac14.github.io/pull/23
0.0.3 to master: https://github.com/karjac14/karjac14.github.io/pull/21

**TIY-Assignments**
Blueprints:
Release 0.0.0 to Master
https://github.com/karjac14/TIY-Assignments/pull/37
Sub-Branch:
Part 1: https://github.com/karjac14/TIY-Assignments/pull/38

Release 0.0.1 to Master
https://github.com/karjac14/TIY-Assignments/pull/39
Sub-Branch:
Part 1: https://github.com/karjac14/TIY-Assignments/pull/42

Release 0.0.2 to Master
https://github.com/karjac14/TIY-Assignments/pull/46
Sub-branches:
https://github.com/karjac14/TIY-Assignments/pull/45
https://github.com/karjac14/TIY-Assignments/pull/48

Release 0.1.0 to Master
https://github.com/karjac14/TIY-Assignments/pull/50
Sub-branches:
https://github.com/karjac14/TIY-Assignments/pull/49

**Comment by al-the-x** [comment]
Please review and close...
