### ISSUE TITLE
HALFTIME -- Kristine Erickson

### ISSUE THREAD

**Issue by ericksonk** [TIY-Durham/2015-FALL-FEE#423]
- [x] **Yak Shaving**
  - [x]  _WIP Issue_: `HALFTIME -- YOUR NAME`
    - [x] link to PRs in `USERNAME.github.io`
    - [x] link to PRs in `TIY-Assignments`
  - [x] _WIP Branch_:
    - [x] `USERNAME.github.io`
      - [x] `journal-week-5`
      - [x] `release-0.0.2` from `master`
      - [x] `feature--remodeling` from `release--0.0.2`
      - [ ] `feature--*` from `release--0.0.2`
    - [x] `TIY-Assignments`
      - [x] `release--0.0.0` from `master`
      - [x] `feature--yak-shaving` from `release--0.0.0`
      - [x] `feature--*` from `release--0.0.1`
  - [x] _WIP Files_:
    - [x] `USERNAME.github.io:release--0.0.2`
      - [x] `_drafts/` -- for any WIP files...
      - [x] `_posts/` -- your completed posts
      - [x] `src/`
        - [x] `scss/*.scss`
        - [x] `js/*.js`
        - [x] `index.html`
      - [x] `bower.json`
      - [x] `package.json`
    - [x] `TIY-Assignments:release--0.0.1`
      - [x] `DropDownMenu` / `SlideOutMenu` / `ResponsiveIcons` / `ResponsiveGrid` -- starting with `yo h5bp`
        - [x] `scss/`
          - [x] `main.scss`
          - [x] `_grid.scss`
          - [ ] `_FEATURE.scss` -- where `FEATURE` is a feature name
        - [x] `specs/` -- with Skitches, of course!
        - [x] `.gitignore` -- ignoring ALL THE THINGS!
        - [x] `bower.json` -- from `bower init` and `bower install`
        - [x] `package.json` -- from `npm init` and `npm install`
        - [x] `index.html` -- with links to all the `bower`-installed packages
- [x] **HALFTIME Journal**
  - [x] **Three's Company**
  - [x] **Build It Out**
  - [x] **Time for some remodeling!**
- **Blueprints Everywhere!**
  - [x] Yaks Shaved
  - [x] Some MFing HTML & SCSS
  - **BEAST MODE** - MORE BLUEPRINTS!
- [ ] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME` -- use the _same_ issue!
    - [ ] Add links to PRs in `USERNAME.github.io`:
      - [ ] from `journal-week-5` into `master`
      - [ ] from `release--0.0.3` into `master`
      - [ ] from `feature--*` into `release--0.0.3`
    - [ ] Add links to PRs in `TIY-Assignments`:
      - [ ] from `release--0.0.2` into `master`
      - [ ] from `feature--*` into `release--0.0.2`
  - [ ]  _WIP Branch_:
    - [ ] `USERNAME.github.io`
      - [ ] `journal-week-5`
      - [ ] `release-0.0.3` from `master`
      - [ ] `feature--*` from `release--0.0.3`
    - [ ] `TIY-Assignments`
      - [ ] `release--0.0.2` from `master`
      - [ ] `feature--*` from `release--0.0.2`
  - [ ] _WIP Files_:
    - [ ] `USERNAME.github.io:journal-week-5`
      - [ ] `journal-week-5.md`
      - [ ] `tutorial-week-5.md`
      - [ ] `resource-week-5.md`
    - [ ] `USERNAME.github.io:release--0.0.3`
      - [ ] `src/`
        - [ ] `js/*.js`
        - [ ] `scss/*.scss`
        - [ ] `index.html`
    - [ ] `TIY-Assignments:release--0.0.2`
      - [ ] `{DropDownMenu,SlideOutMenu}/`
        - [ ] `js/*.js`
        - [ ] `scss/*.scss`
        - [ ] `index.html`
      - [ ] `{ResponsiveIcons,ResponsiveGrid}/`
        - [ ] **BEAST MODE** `js/*.js`
        - [ ] `scss/*.scss`
        - [ ] `index.html`
- [ ] **HALFTIME Journal!**
  - [ ] Week 5 Journal was due _today!_
  - [ ] Week 5 Tutorial due on _Monday!_
  - [ ] Week 5 Resource should _already be done!_
- [ ] **Finishing Up the Features**
  - [ ] Move on to `release--0.0.3`!
  - [ ] Cut the fat! _Just essential features!_
  - [ ] Get Peer Reviews that _include feedback!_
- [ ] **Blueprints Everywhere!**
  - [x] Move on to `release--0.0.2`!
  - [ ] Maybe get to `release--0.1.0`...?
  - [ ] What version should you be on by Monday?
  - [ ] **BEAST MODE** How about some JavaScript?

**Comment by ericksonk** [comment]
Blueprints Everywhere
`release--0.0.0` PR: https://github.com/ericksonk/TIY-Assignments/pull/26
`release--0.0.1` PR: https://github.com/ericksonk/TIY-Assignments/pull/28

`feature--specs` PR: https://github.com/ericksonk/TIY-Assignments/pull/27
`feature--drop-down-basic-html` PR: https://github.com/ericksonk/TIY-Assignments/pull/29
`feature--drop-down-basic-css` PR: https://github.com/ericksonk/TIY-Assignments/pull/30
`feature--icon-grid-basic-layout` PR: https://github.com/ericksonk/TIY-Assignments/pull/31

`release--0.0.2` PR: https://github.com/ericksonk/TIY-Assignments/pull/34
`feature--drop-menu-desktop` PR: https://github.com/ericksonk/TIY-Assignments/pull/33
`feature--drop-menu-js` PR: https://github.com/ericksonk/TIY-Assignments/pull/35
`feature--drop-menu-tablet` PR:
`feature--drop-menu-mobile` PR:

`realease--0.0.3` PR: https://github.com/ericksonk/TIY-Assignments/pull/37
`feature--icon-grid-header` PR: https://github.com/ericksonk/TIY-Assignments/pull/36
`feature--icon-grid-gridlayout` PR: https://github.com/ericksonk/TIY-Assignments/pull/38
`feature--icon-grid-hover` PR: https://github.com/ericksonk/TIY-Assignments/pull/39
`feature--icon-grid-tablet` PR: https://github.com/ericksonk/TIY-Assignments/pull/40
`feature--icon-grid-mobile` PR: https://github.com/ericksonk/TIY-Assignments/pull/41
`feature--drop-menu-restructure` PR: https://github.com/ericksonk/TIY-Assignments/pull/42
- [ ] `TIY-Assignments:
  - [x] New branch `release--0.0.0`
    - [x] Create folder `DropDownMenu`
      - [x] starting with `yo h5bp`
        - [x] `scss/`
          - [x] `main.scss`
          - [x] `_grid.scss`
          - [x] `_FEATURE.scss` -- where `FEATURE` is a feature name
      - [x] `specs/` -- with Skitches, of course!
      - [x] `.gitignore` -- ignoring ALL THE THINGS!
      - [x] `bower.json` -- from `bower init` and `bower install`
      - [x] `package.json` -- from `npm init` and `npm install`
      - [x] `index.html` -- with links to all the `bower`-installed packages
    - [x] Create folder `ResponsiveGrid` 
      - [x] starting with `yo h5bp`
        - [x] `scss/`
          - [x] `main.scss`
          - [x] `_grid.scss`
          - [ ] `_FEATURE.scss` -- where `FEATURE` is a feature name
  - [x] New branch `release--0.0.1`
    - [x] create feature branch `feature--drop-down-basic-html`
    - [x] create feature branch `feature--drop-down-basic-css`
    - [x] create feature branch `feature--icon-grid-basic-layout`
    - [x] create feature branch `feature--drop-menu-js`
    - [ ] create feature branch `feature--drop-menu-tablet`
    - [ ] create feature branch `feature--drop-menu-mobile`
    - [x] create feature branch `feature-icon-grid-header`
    - [x] create feature branch `feature--icon-grid-gridlayout`
    - [x] create feature branch `feature--icon-grid-hover`
    - [x] create feature branch `feature--icon-grid-tablet`
    - [x] create feature branch `feature--icon-grid-mobile`

**Comment by ericksonk** [comment]
Build It Out
`release--0.0.2` PR: https://github.com/ericksonk/ericksonk.github.io/pull/21
(accidentally did yak-shaving on `release` instead of feature branch)

`feature--remodeling` PR: https://github.com/ericksonk/ericksonk.github.io/pull/22
Peer Review:
https://github.com/rosalsm/rosalsm.github.io/pull/23
https://github.com/jeffworley/jeffworley.github.io/pull/27

`release--0.0.3` PR: https://github.com/ericksonk/ericksonk.github.io/pull/25
`feature--blog-basic-layout` PR: https://github.com/ericksonk/ericksonk.github.io/pull/24
`feature--blog-header` PR: https://github.com/ericksonk/ericksonk.github.io/pull/26
`feature--blog-list` PR: https://github.com/ericksonk/ericksonk.github.io/pull/27
`feature--blog-nav` PR: https://github.com/ericksonk/ericksonk.github.io/pull/28
`feature--blog-about-column` PR: https://github.com/ericksonk/ericksonk.github.io/pull/29
`feature--blog-js` PR: https://github.com/ericksonk/ericksonk.github.io/pull/30
- [x] `feature--blog-basic-layout`
  - [x] basic html
  - [x] basic css
- [x] `feature--header
  - [x] `<nav>` bar in small column
  - [ ] heading image big column
- [x] `feature--blog-list
  - [ ] `<h4>`
  - [x] paragraph content
  - [x] continue reading link
  - [x] `bottom-border:`
- [x] `feature--about-column`
  - [ ] `<ul>` ?
  - [ ] social media buttons
- [x] `feature--blog-js
  - [x] set character limit
  - [ ] continue reading button
- [ ] `feature--blog-tablet`
- [ ] `feature--blog-mobile`

**Comment by ericksonk** [comment]
Journal/Tutorial/Resource Final Drafts PR: https://github.com/ericksonk/ericksonk.github.io/pull/23

**Comment by al-the-x** [comment]
Please review and close...
