### ISSUE TITLE
HALFTIME -- Lacey Rice

### ISSUE THREAD

**Issue by Ricecoder** [TIY-Durham/2015-FALL-FEE#424]
- [ ] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME`
    - [ ] link to PRs in `USERNAME.github.io`
    - [ ] link to PRs in `TIY-Assignments`
  - _WIP Branch_:
    - `USERNAME.github.io`
      - [x] `journal-week-5`
      - [x] `release-0.0.2` from `master`
      - [x] `feature--remodeling` from `release--0.0.2`
      - [ ] `feature--*` from `release--0.0.2`
    - `TIY-Assignments`
      - [x] `release--0.0.0` from `master`
      - [x] `feature--yak-shaving` from `release--0.0.0`
      - [ ] `feature--*` from `release--0.0.1`
  - _WIP Files_:
    - `USERNAME.github.io:release--0.0.2`
      - [x] `_drafts/` -- for any WIP files...
      - [x] `_posts/` -- your completed posts
      - [ ] `src/`
        - [x] `scss/*.scss`
        - [ ] `js/*.js`
        - [x] `index.html`
      - [x] `bower.json`
      - [x] `package.json`
    - `TIY-Assignments:release--0.0.1`
      - [x] `DropDownMenu` / `SlideOutMenu` / `ResponsiveIcons` / `ResponsiveGrid` -- starting with `yo h5bp`
        - [x] `scss/`
          - [x] `main.scss`
          - [x] `_grid.scss`
          - [x] `_FEATURE.scss` -- where `FEATURE` is a feature name
        - [ ] `specs/` -- with Skitches, of course!
        - [x] `.gitignore` -- ignoring ALL THE THINGS!
        - [x] `bower.json` -- from `bower init` and `bower install`
        - [x] `package.json` -- from `npm init` and `npm install`
        - [x] `index.html` -- with links to all the `bower`-installed packages
- **HALFTIME Journal**
  - [x] **Three's Company**
  - [x] **Build It Out**
  - [x] **Time for some remodeling!**
- **Blueprints Everywhere!**
  - [x] Yaks Shaved
  - [ ] Some MFing HTML & SCSS
  - **BEAST MODE** - MORE BLUEPRINTS!

**HALFTIME PART 2**
- [ ] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME` -- use the _same_ issue!
    - Add links to PRs in `USERNAME.github.io`:
      - from `journal-week-5` into `master`
      - from `release--0.0.3` into `master`
      - from `feature--*` into `release--0.0.3`
    - Add links to PRs in `TIY-Assignments`:
      - from `release--0.0.2` into `master`
      - from `feature--*` into `release--0.0.2`
  -  _WIP Branch_:
    - `USERNAME.github.io`
      - `journal-week-5`
      - `release-0.0.3` from `master`
      - `feature--*` from `release--0.0.3`
    - `TIY-Assignments`
      - `release--0.0.2` from `master`
      - `feature--*` from `release--0.0.2`
  - _WIP Files_:
    - `USERNAME.github.io:journal-week-5`
      - `journal-week-5.md`
      - `tutorial-week-5.md`
      - `resource-week-5.md`
    - `USERNAME.github.io:release--0.0.3`
      - `src/`
        - `js/*.js`
        - `scss/*.scss`
        - `index.html`
    - `TIY-Assignments:release--0.0.2`
      - `{DropDownMenu,SlideOutMenu}/`
        - `js/*.js`
        - `scss/*.scss`
        - `index.html`
      - `{ResponsiveIcons,ResponsiveGrid}/`
        - **BEAST MODE** `js/*.js`
        - `scss/*.scss`
        - `index.html`
- [x] **HALFTIME Journal!**
  - Week 5 Journal was due _today!_
  - Week 5 Tutorial due on _Monday!_
  - Week 5 Resource should _already be done!_
- [ ] **Finishing Up the Features**
  - Move on to `release--0.0.3`!
  - Cut the fat! _Just essential features!_
  - Get Peer Reviews that _include feedback!_
- [ ] **Blueprints Everywhere!**
  - Move on to `release--0.0.2`!
  - Maybe get to `release--0.1.0`...?
  - What version should you be on by Monday?
  - **BEAST MODE** How about some JavaScript?

**Comment by Ricecoder** [comment]
RICECODER.GITHUB.IO PRS:

journal--week-5 into master
https://github.com/Ricecoder/ricecoder.github.io/pull/24

release--0.0.2 into master
https://github.com/Ricecoder/ricecoder.github.io/pull/27

feature--remodeling into release--0.0.2
https://github.com/Ricecoder/ricecoder.github.io/pull/26

feature--hamburger-menu into release--0.0.2
https://github.com/Ricecoder/ricecoder.github.io/pull/28

feature--image-header into release--0.0.2
https://github.com/Ricecoder/ricecoder.github.io/pull/29

**Comment by Ricecoder** [comment]
COMMENTS:
https://github.com/ericquayson/TIY-Assignments/pull/27
https://github.com/jmcreasman/jmcreasman.github.io/pull/12
https://github.com/boshnivolo/boshnivolo.github.io/pull/17

**Comment by Ricecoder** [comment]
TIY-ASSIGNMENTS PRs:

release--0.0.0 into master
https://github.com/Ricecoder/TIY-Assignments/pull/19

feature--horizontal-slide-out into release--0.0.1
https://github.com/Ricecoder/TIY-Assignments/pull/20

feature--responsive-icon-grid into release--0.0.2
https://github.com/Ricecoder/TIY-Assignments/pull/22

release--0.0.2 into master 
https://github.com/Ricecoder/TIY-Assignments/pull/23

feature--horizontal-mobile into release--0.0.3
https://github.com/Ricecoder/TIY-Assignments/pull/24

release--0.0.3 into master
https://github.com/Ricecoder/TIY-Assignments/pull/25

**Comment by Ricecoder** [comment]
BUILD IT OUT: Feature: Hamburger Menu with Horizontal Slide Out Side Menu:
- [ ] Basic HTML
  - `<a href="#">` for hamburger icon and all `<li>`
  - `<ul>` for side menu
- [ ] Basic Styling
  - `visibility: hidden` for `<ul>` maybe on `.hidden` class
- [ ] Basic Layout
- [ ] JavaScript
  - `.on('click')` for hamburger icon. 
  - needs to remove `hidden` class from `<ul>` when hamburger icon clicked.

**Comment by al-the-x** [comment]
Please review and close...
