### ISSUE TITLE
HALFTIME -- Jonathan Creasman

### ISSUE THREAD

**Issue by jmcreasman** [TIY-Durham/2015-FALL-FEE#425]
- [x] **Yak Shaving**
  - _WIP Issue_: `HALFTIME -- YOUR NAME`
    - link to PRs in `USERNAME.github.io`
    - link to PRs in `TIY-Assignments`
  - _WIP Branch_:
    - `USERNAME.github.io`
      - `journal-week-5`
      - `release-0.0.2` from `master`
      - `feature--remodeling` from `release--0.0.2`
      - `feature--*` from `release--0.0.2`
    - `TIY-Assignments`
      - `release--0.0.0` from `master`
      - `feature--yak-shaving` from `release--0.0.0`
      - `feature--*` from `release--0.0.1`
  - _WIP Files_:
    - `USERNAME.github.io:release--0.0.2`
      - `_drafts/` -- for any WIP files...
      - `_posts/` -- your completed posts
      - `src/`
        - `scss/*.scss`
        - `js/*.js`
        - `index.html`
      - `bower.json`
      - `package.json`
    - `TIY-Assignments:release--0.0.1`
      - `DropDownMenu` / `SlideOutMenu` / `ResponsiveIcons` / `ResponsiveGrid` -- starting with `yo h5bp`
        - `scss/`
          - `main.scss`
          - `_grid.scss`
          - `_FEATURE.scss` -- where `FEATURE` is a feature name
        - `specs/` -- with Skitches, of course!
        - `.gitignore` -- ignoring ALL THE THINGS!
        - `bower.json` -- from `bower init` and `bower install`
        - `package.json` -- from `npm init` and `npm install`
        - `index.html` -- with links to all the `bower`-installed packages
- **HALFTIME Journal**
  - [x] **Three's Company**
  - [x] **Build It Out**
  - [x] **Time for some remodeling!**
- **Blueprints Everywhere!**
  - [x] Yaks Shaved
  - [x] Some MFing HTML & SCSS
  - **BEAST MODE** - MORE BLUEPRINTS!

**Comment by jmcreasman** [comment]
Links to PRs
USERNAME.github.io
journal-week-5
https://github.com/jmcreasman/jmcreasman.github.io/pull/12

Blog Site
from release-0.0.2 into master
https://github.com/jmcreasman/jmcreasman.github.io/pull/17

from feature--remodeling into release 0.0.2
https://github.com/jmcreasman/jmcreasman.github.io/pull/18

from feature--sidebar into release0.0.2
https://github.com/jmcreasman/jmcreasman.github.io/pull/19

from release-0.0.3 into master
https://github.com/jmcreasman/jmcreasman.github.io/pull/20

from feature--navbar into release0.0.3
https://github.com/jmcreasman/jmcreasman.github.io/pull/21

from feature--nav--html into feature--navbar
https://github.com/jmcreasman/jmcreasman.github.io/pull/22

from feature--nav--css into feature--navbar
https://github.com/jmcreasman/jmcreasman.github.io/pull/23

from release-0.0.4 into master
https://github.com/jmcreasman/jmcreasman.github.io/pull/24

from feature--featured--blog into release-0.0.4
https://github.com/jmcreasman/jmcreasman.github.io/pull/25

from feature--sidebar--blogger--bio into release-0.0.4
https://github.com/jmcreasman/jmcreasman.github.io/pull/26

from feature--picture--slider into release-0.0.4
https://github.com/jmcreasman/jmcreasman.github.io/pull/27

from release-1.0.0 into master
https://github.com/jmcreasman/jmcreasman.github.io/pull/28

from feature--categories into release-1.0.0
https://github.com/jmcreasman/jmcreasman.github.io/pull/29

from feature--icons into release-1.0.0
https://github.com/jmcreasman/jmcreasman.github.io/pull/30

TIY-Assignments
from release 0.0.0 into master
https://github.com/jmcreasman/TIY-Assignments/pull/22

from release 0.0.1 into master
https://github.com/jmcreasman/TIY-Assignments/pull/23

from feature--html into release 0.0.1
https://github.com/jmcreasman/TIY-Assignments/pull/24

from release 0.0.2 into master
https://github.com/jmcreasman/TIY-Assignments/pull/25

from feature--css into release 0.0.2
https://github.com/jmcreasman/TIY-Assignments/pull/26

from feature--adddetails into release 0.0.2
https://github.com/jmcreasman/TIY-Assignments/pull/28

from release 0.0.3 into master
https://github.com/jmcreasman/TIY-Assignments/pull/29

from feature--js into release 0.0.3
https://github.com/jmcreasman/TIY-Assignments/pull/31

from feature--cleanup into release 0.0.3
https://github.com/jmcreasman/TIY-Assignments/pull/32

**Comment by al-the-x** [comment]
Please review and close...
