### ISSUE TITLE
00 Matt Oliverio

### ISSUE THREAD

**Issue by ironyarder77** [TIY-Durham/2015-FALL-FEE#45]

**Comment by ironyarder77** [comment]
- [ ] **GitHub-ing to Know You**
  - [x] [Create a GitHub account](https://github.com/signup)
  - [x] [Edit your GitHub profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so we can recognize your face.
  - [x] Your full name, so we can recognize your name.
  - [x] A valid public email address, so we can contact you.
  - [x] Find and star [the class project](https://github.com/TIY-Durham/2015-FALL-FEE)
  - [x] Read [the Home page on the class wiki](https://github.com/TIY-Durham/2015-FALL-FEE/wiki)
- [x] **You've Got Issues**
  - [x] [Create a new _WIP Issue_](https://github.com/TIY-Durham/2015-FALL-FEE/issues/new)
  - [x] Name it `00 -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] Make this checklist the description
  - [x] Start checking off boxes... :astonished:
- [x] **Send all my GitHub to you...**
  - [x] Learn all you can about `git` and GitHub!
    - Treehouse has [a Git Basics course](http://teamtreehouse.com/library/git-basics)
  - CodeSchool has [a `git` path](https://www.codeschool.com/paths/git)
    - [ ] Complete: [Try Git](http://try.github.com)
  - [ ] GitHub has a couple of Guides:
    - [ ] [Hello World](https://guides.github.com/activities/hello-world/)
    - [ ] [Forking Projects](https://guides.github.com/activities/forking/)
  - [ ] Add a link to your `Hello-World` and `Fork-and-Spoon` repos as a comment on your _WIP Issue_
- [ ] **Command Line Training**
  - [ ] Read: http://eddywashere.com/blog/an-intro-to-the-os-x-command-line/
  - [ ] Complete: https://www.codecademy.com/courses/learn-the-command-line/
  - [ ] **BEAST MODE** http://cli.learncodethehardway.org/book/
- [ ] **INSTALL ALL THE THINGS!**
  - [ ] [Install Homebrew](http://brew.sh) on your Mac
  - [ ] Open `Terminal.app`; Don't Panic.
  - [ ] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [ ] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
  - [ ] Using the `brew` command, install the following packages:
    - [ ] `zsh`
  - [ ] `git`
  - [ ] `hub`
  - [ ] `node`
  - [ ] Add the output of the following commands as comments on your _WIP Issue_:
    - [ ] `which zsh && zsh --version`
    - [ ] `which git && git --version`
    - [ ] `which hub && hub --version`
    - [ ] `which node && node --version`
  - [ ] Install the following (bonus if you use `brew`):
    - [ ] [Google Chrome](http://google.com/chrome)
    - [ ] [Atom](http://atom.io)
    - [ ] [Dash](http://kapeli.com/dash)
    - [ ] [Slack](http://www.slack.com)
    - [ ] [SourceTree](https://www.sourcetreeapp.com/)
- [ ] **Prezto Change-oh!**
  - [ ] Find and _fork_ the Prezto project on GitHub
  - [ ] Clone _your fork_ of Prezto into your home directory
  - [ ] Follow the installation instructions in the `README.md` file
- [ ] **Take a Moment to Reflect**
  - [ ] Answered question 1 in a comment on your WIP Issue.
  - [ ] Answered question 2 in a comment on your WIP Issue.

**Comment by ironyarder77** [comment]
If I had seen this direct instruction from David I wouldn't have been so confused about how we were starting and what tools we were going to be using.
For instance, I am only now taking the CLI crash course.  Either way I am still going to do these exercises and check my boxes for Ready Player One...for my own benefit.
My goal at this point is to be extremely fluid in GitHub and comfortable w/ using it as a means to work on and submit projects.

**Comment by kellymurray** [comment]
@ironyarder77 it's great that you want to track your efforts in an issue. However, please open this issue on your `TIY-Assignments` repo and close this one here. The issues on `2015-FALL-FEE` are for current assignments only. Thank you! Please let me know if you need any help doing this.

**Comment by al-the-x** [comment]
Please review and close...

**Comment by al-the-x** [comment]
Just testing my robot. It appears to be working!
