### ISSUE TITLE
02 -- Jonathan Creasman 2.0

### ISSUE THREAD

**Issue by jmcreasman** [TIY-Durham/2015-FALL-FEE#63]
- [x] **Yak Shaving**
  - [x] Open a new WIP Issue in the Class Repo:
    - [x] Named `02 -- YOUR NAME` where `YOUR NAME` is _your full name_
    - [x] Copy-and-paste this checklist into the description!
    - [x] Check off your checkboxes as you complete tasks!
  - [x] **MERGED THOSE PRs ALREADY!**
  - [x] Fork the `TIY-Durham/javascript-koans` repository!
  - [x] Created new _WIP Branches_ in:
    - [x] `USERNAME.github.io` named `rough-draft` (`USERNAME.github.io:rough-draft`)
    - [x] `TIY-Assignments` named `02--fellowship-of-the-string` (`TIY-Assignments:02--fellowship-of-the-string`)
    - [x] Your _forked_ `javascript-koans` repo named `2014-09-01` (`javascript-koans:2014-09-01`)
  - [x] Create new _WIP Files_ in:
    - [x] `TIY-Assignments`:
      - [x] `BasicCalculator.js` from the **Starting Point**
      - [x] `StringCalculator.js` from the **Starting Point**
  - [x] Update _existing_ files in:
    - [x] `USERNAME.github.io`: `the-right-mindset.md`
    - [x] `TIY-Assignments`: `ReadingJavaScript/README.md`
    - [x] _your forked_ `javascript-koans` in `koans/`
  - [x] Create new PRs in:
    - [x] `USERNAME.github.io` _from_ `rough-draft` _into_ `master`
    - [x] _your forked_ `javascript-koans` _from_ `2015-09-01` _into_ `master`
    - [x] `TIY-Assignments` _from_ `02--fellowship-of-the-ring` _into_ `master`
  - [x] LINK DEM PRs!
- [x] **The Right Mindset: Rought Draft**
  - [x] Create a new branch in your `USERNAME.github.io` repo called `rough-draft`
  - [x] In the `rough-draft` branch, write an initial outline in `the-right-mindset.md`
  - [x] Open a Pull Request from `rough-draft` to `master`
  - [x] Add a link to that PR in your WIP Issue
  - [x] Add some rough drafts to `the-right-mindset.md` over a few commits
- [x] **Reading JavaScript**
  - [x] added 2 more entries
  - [x] added 5 more entries
  - [x] added 10 entries!
  - [x] added 1 "weirdo" operator
  - [x] added `function`
    - [x] example function definition
    - [x] example function invocation
- [ ] **JavaScript Koans**
  - [x] **Yak Shaving**
    - [x] Fork `TIY-Durham/javascript-koans` into your own account
    - [x] Create a _WIP Branch_ called `2015-09-01`
    - [x] Clone your forked repo locally into your `TIY` folder
    - [x] Open your clone in `Terminal.app`
  - [x] **Getting Started**
    - [x] Run `npm install` inside the cloned repo; 
    - [x] Run `npm start` inside the cloned repo
    - [x] Add a comment to your _WIP Issue_ explaining what happened...
  - [ ] **Normal Mode**
    - [x] completed: `AboutExpects`
    - [ ] completed: `AboutArrays`
    - [ ] completed: `AboutFunctions`
  - [x] Did you open your PR yet?
  - **BEAST MODE**
    - completed: `AboutObjects`
    - completed: `AboutMutability`
    - completed: `AboutHigherOrderFunctions`
  - **NIGHTMARE MODE**
    - completed everything!
- [ ] **Coding Kata: Basic Calculator**
  - [x] Created _WIP Branch_ in `TIY-Assignments`
  - [x] Created `BasicCalculator.js` in _WIP Branch_
  - [ ] `add` exists!
  - [ ] checked `add` for... 
    - [ ] `0` added to `0`... that was easy
    - [ ] `0` added to `1` through `5`
    - [ ] `0` added to `6` through `9`
    - [ ] `1` added to... uh oh.
    - [ ] up to `5`...!
    - [ ] all the way to `9 + 9`...!
  - [ ] `minus` exists!
  - [ ] checked `minus` for...
    - [ ] `0` minus everything...
    - [ ] up to `5` minus `5`
    - [ ] `9` minus `9`
  - [ ] `times` exists!
  - [ ] `times` tested!
  - [ ] `divide` exists!
  - [ ] `divide` tested... except.
  - [ ] what is anything divided by `0`...?
  - **BEAST MODE** -- `pow` of `0` through `9`...?
  - **NIGHTMARE MODE** -- Smarter tests?
- [ ] **Coding Kata: String Calculator**
  - [ ] function `toNumber` exists!
  - [ ] `toNumber("zero")` works!
  - [ ] function `add` exists!
  - [ ] `add("zero", "zero")` works!
  - [ ] `"one"` plus `"one"` is `2`!
  - [ ] `"two"` plus `"two"` is `4`!
  - [ ] make `"seven"` up yours!
  - [ ] and `"nine"` is the end!
  - [ ] First pair!
  - [ ] Second pair!
  - [ ] Third pair!

**Comment by jmcreasman** [comment]
Link to my Javascript documentation where I'm adding new terms (it's under the yak shaving branch, and I'm not sure if it should be moved to another branch).
https://github.com/jmcreasman/TIY-Assignments/blob/yak-shaving/ReadingJavaScript/README.md

LINK DEM PRs:

USERNAME.github.io from rough-draft into master
https://github.com/jmcreasman/jmcreasman.github.io/pull/4

your forked javascript-koans from 2015-09-01 into master
https://github.com/jmcreasman/javascript-koans/pull/1

TIY-Assignments from 02--fellowship-of-the-ring into master
https://github.com/jmcreasman/TIY-Assignments/pull/1

**Comment by jmcreasman** [comment]
Add a comment to your WIP Issue explaining what happened...

I ran npm start and it looks like it took the javascript-koans.js script and evaluated the code giving them either a passing or failing mark. Also the command line has disappeared from the terminal until I type "control c" to bring it back.

**Comment by jmcreasman** [comment]
Link to my About JavaScript page
https://github.com/jmcreasman/jmcreasman.github.io/wiki/The-Right-Mindset

**Comment by kellymurray** [comment]
Given incomplete because:
- String Calculator not turned in

Please review and close.
