### ISSUE TITLE
00 -- KRISTINE ERICKSON

### ISSUE THREAD

**Issue by ericksonk** [TIY-Durham/2015-FALL-FEE#7]
- [ ] **GitHub-ing to Know You**
  - [x] [Create a GitHub account](https://github.com/signup)
  - [x] [Edit your GitHub profile](https://github.com/settings/profile) to provide:
  - [x] A picture, so we can recognize your face.
  - [x] Your full name, so we can recognize your name.
  - [x] A valid public email address, so we can contact you.
  - [x] Find and star [the class project](https://github.com/TIY-Durham/2015-FALL-FEE)
  - [ ] Read [the Home page on the class wiki](https://github.com/TIY-Durham/2015-FALL-FEE/wiki)
- [x] **You've Got Issues**
  - [x] [Create a new _WIP Issue_](https://github.com/TIY-Durham/2015-FALL-FEE/issues/new)
  - [x] Name it `00 -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] Make this checklist the description
  - [x] Start checking off boxes... :astonished:
- [ ] **Send all my GitHub to you...**
  - [ ] Learn all you can about `git` and GitHub!
    - Treehouse has [a Git Basics course](http://teamtreehouse.com/library/git-basics)
  - CodeSchool has [a `git` path](https://www.codeschool.com/paths/git)
    - [x] Complete: [Try Git](http://try.github.com)
  - [x] GitHub has a couple of Guides:
    - [x] [Hello World](https://guides.github.com/activities/hello-world/)
    - [x] [Forking Projects](https://guides.github.com/activities/forking/)
  - [ ] Add a link to your `Hello-World` and `Fork-and-Spoon` repos as a comment on your _WIP Issue_
- [ ] **Command Line Training**
  - [x] Read: http://eddywashere.com/blog/an-intro-to-the-os-x-command-line/
  - [ ] Complete: https://www.codecademy.com/courses/learn-the-command-line/
  - [ ] **BEAST MODE** http://cli.learncodethehardway.org/book/
- [ ] **INSTALL ALL THE THINGS!**
  - [x] [Install Homebrew](http://brew.sh) on your Mac
  - [x] Open `Terminal.app`; Don't Panic.
  - [ ] [Install Homebrew and the `brew` command](http://brew.sh/#install)
  - [ ] Read [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
  - [ ] Using the `brew` command, install the following packages:
    - [ ] `zsh`
  - [x] `git`
  - [ ] `hub`
  - [x] `node`
  - [ ] Add the output of the following commands as comments on your _WIP Issue_:
    - [ ] `which zsh && zsh --version`
    - [ ] `which git && git --version`
    - [ ] `which hub && hub --version`
    - [ ] `which node && node --version`
  - [ ] Install the following (bonus if you use `brew`):
    - [x] [Google Chrome](http://google.com/chrome)
    - [x] [Atom](http://atom.io)
    - [x] [Dash](http://kapeli.com/dash)
    - [x] [Slack](http://www.slack.com)
    - [ ] [SourceTree](https://www.sourcetreeapp.com/)
- [ ] **Prezto Change-oh!**
  - [ ] Find and _fork_ the Prezto project on GitHub
  - [ ] Clone _your fork_ of Prezto into your home directory
  - [ ] Follow the installation instructions in the `README.md` file
- [ ] **Take a Moment to Reflect**
  - [ ] Answered question 1 in a comment on your WIP Issue.
  - [ ] Answered question 2 in a comment on your WIP Issue.

**Comment by kellymurray** [comment]
Incomplete given because:
- Please follow the instructions and add issues for your answers.
- Please remember to check off boxes as you complete items.
- Please come see me if you need help installing the items you did not check.
- Please complete Prezto Change-oh!
- Please complete Take a Moment to Reflect.
- Git Basics course.

Please remember, it is important that you try everything.

@ericksonk please review and close.
